kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: depends-on-role-consumer
  namespace: default
rules:
  - apiGroups: ["batch", "apps", ""]
    resources: ["pods", "services", "jobs"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: depends-on-role-consumer-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "consumer.serviceAccountName" . }}
roleRef:
  kind: Role
  name: depends-on-role-consumer
  apiGroup: rbac.authorization.k8s.io